kind: pipeline
name: latest
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ikifar/hastebin-server
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password